language: java
jdk: oraclejdk8
dist: trusty
services:
  - docker
sudo: false

cache:
  directories:
    - $HOME/.m2

install: true
script:
  - ./tools/build/build_and_run_unit.sh
  - ./tools/build/docker_image.sh