language: java
jdk: oraclejdk8
dist: trusty
services:
  - docker
sudo: false
cache:
  directories:
    - "$HOME/.m2"

before_install:
  - openssl aes-256-cbc -K $encrypted_f960f87b33d5_key -iv $encrypted_f960f87b33d5_iv -in ./k8s/config.yaml.enc -out ./k8s/config.yaml -d
  - mv ./k8s/config.yaml $HOME/.kube/config
  - wget https://kubernetes-helm.storage.googleapis.com/helm-v2.9.1-linux-amd64.tar.gz
  - tar xzvf helm-v2.9.1-linux-amd64.tar.gz
  - mv linux-amd64/helm helm
  - chmod +x helm
  - ./helm init -c
script:
  - ./tools/build/build_and_run_unit.sh
  - ./tools/build/docker_image.sh
  - ./tools/build/deploy.sh