language: java
jdk: oraclejdk8
dist: trusty
services:
  - docker
sudo: false

before_install:
  - wget https://kubernetes-helm.storage.googleapis.com/helm-v2.9.1-linux-amd64.tar.gz
  - tar xzvf helm-v2.9.1-linux-amd64.tar.gz
  - mv linux-amd64/helm /usr/local/bin/helm
  - chmod u+x /usr/local/bin/helm
  - helm init -c

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: Build and run unit tests
      script:
        - ./tools/build/build_and_run_unit.sh
    - stage: Build and push docker image
      script:
        - ./tools/build/docker_image.sh
    - stage: Deploy to kubernetes
      script:
        - echo "TODO"