POST {{host}}/users/login
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}

###

POST {{host}}/users/create
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}


### These APIs are not public
###

GET localhost:8080/health/readiness

###
GET localhost:8080/health/liveness

###